# Common tmux configs and key bindings

set -g mouse on
setw -g mode-keys vi

# set the scroll speed to one line at a time
bind -Tcopy-mode WheelUpPane send -N1 -X scroll-up
bind -Tcopy-mode WheelDownPane send -N1 -X scroll-down


# Start windows and panes # with 1 (not 0), and renumber on close.
set -g base-index 1
set -g pane-base-index 1

bind-key x kill-pane

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind -r K resize-pane -U 5
bind -r J resize-pane -D 5

bind -n M-h previous-window
bind -n M-l next-window
bind-key a last-window
# Jump to window using alt+number 
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
